name: "P6 GHA: Upgrade Dependencies for NextJS Static Site"
description: "P6 GHA: Upgrade Dependencies for NextJS Static Site"
author: "Philip M. Gollucci"
inputs:
  gh_token:
    description: "GitHub Token"
    required: true
  git_token:
    description: "Git token for branch operations"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: p6m7g8-actions/checkout@main
      with:
        fetch-depth: 0
    - name: Force main branch
      shell: bash
      run: |
        git fetch origin main
        git checkout -B main origin/main
    - name: Node
      uses: p6m7g8-actions/node-setup@main
    - name: Update Dependencies
      shell: bash
      run: |
        pnpm up --latest --prod
        pnpm add -D tailwindcss@^3.4.18
    - name: Generate Delta
      shell: bash
      run: |
        git diff
    - name: Create Pull Request
      id: create_pr
      uses: peter-evans/create-pull-request@v7.0.8
      with:
        token: ${{ inputs.git_token }}
        branch-token: ${{ inputs.git_token }}
        commit-message: |
          chore(deps): upgrade dependencies
        base: main
        branch: github-actions/upgrade-main
        title: "chore(deps): upgrade dependencies"
        labels: auto-merge
        body: |
          Upgrades project dependencies.
        author: github-actions <github-actions@github.com>
        committer: github-actions <github-actions@github.com>
        signoff: true
